# Generated by Django 4.0.3 on 2023-03-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey_templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.TextField(blank=True)),
                ('config', models.TextField(blank=True)),
                ('welcome_screen', models.TextField(blank=True)),
                ('thank_you_screen', models.TextField(blank=True)),
                ('survey_staus', models.BooleanField(default=True)),
                ('creation_date_time', models.TextField(default='2023-03-10 14:17:42.595596+05:30')),
            ],
        ),
    ]
