# Generated by Django 4.0.3 on 2023-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('survey', models.TextField(blank=True)),
                ('config', models.TextField(blank=True)),
                ('welcome_screen', models.TextField(blank=True)),
                ('thank_you_screen', models.TextField(blank=True)),
                ('survey_staus', models.BooleanField(default=True)),
                ('creation_date_time', models.TextField(default='2023-03-10 14:46:18.268598+05:30')),
            ],
        ),
        migrations.AlterField(
            model_name='survey_templates',
            name='creation_date_time',
            field=models.TextField(default='2023-03-10 14:46:18.268598+05:30'),
        ),
    ]
