# Generated by Django 4.0.3 on 2023-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_user_surveys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.TextField()),
                ('survey', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='survey_templates',
            name='creation_date_time',
            field=models.TextField(default='2023-03-10 16:17:53.937223+05:30'),
        ),
        migrations.AlterField(
            model_name='user_surveys',
            name='creation_date_time',
            field=models.TextField(default='2023-03-10 16:17:53.937223+05:30'),
        ),
    ]
