# Generated by Django 4.0.3 on 2023-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('uid', models.TextField()),
                ('creation_date_time', models.TextField(default='2023-03-10 12:05:59.611512+05:30')),
            ],
        ),
    ]
