# Generated by Django 4.0.3 on 2023-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAppAuth', '0002_alter_user_data_creation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='creation_date_time',
            field=models.TextField(default='2023-03-10 14:46:18.270970+05:30'),
        ),
    ]
