# Generated by Django 4.0.3 on 2023-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAppAuth', '0003_alter_user_data_creation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='creation_date_time',
            field=models.TextField(default='2023-03-10 16:17:53.938221+05:30'),
        ),
    ]
