# Generated by Django 4.0.3 on 2023-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAppAuth', '0005_alter_user_data_creation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='creation_date_time',
            field=models.TextField(default='2023-03-13 14:18:53.504223+05:30'),
        ),
    ]
